# Generated by Django 2.2.4 on 2019-08-15 01:57

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190814_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('info', wagtail.core.fields.RichTextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
