# Generated by Django 2.2.4 on 2019-08-11 18:48

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='left_col',
            field=wagtail.core.fields.RichTextField(default='some text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='right_col',
            field=wagtail.core.fields.RichTextField(default='some text'),
            preserve_default=False,
        ),
    ]
