# Generated by Django 2.2.4 on 2019-08-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_resource_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='info',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
