# Generated by Django 2.2.4 on 2019-08-15 02:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_resource_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='info',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
