# Generated by Django 2.2.4 on 2019-08-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190815_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecatsorderable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ResourceCategory'),
        ),
    ]
