# Generated by Django 2.2.4 on 2019-08-16 13:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190816_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCatsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
        migrations.AddField(
            model_name='resourcecatsorderable',
            name='resource',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.Resource'),
        ),
    ]
