# Generated by Django 2.2.4 on 2019-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceservice', '0004_resourcelistingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
